FROM node:17.3.0-alpine3.14
WORKDIR /app
ENV PATH "/app/node_modules/.bin:$PATH"
COPY package.json ./
RUN apk add --no-cache bash
RUN yarn install --silent
COPY . ./
RUN ./buildWithPrefix https://ggia-dev.ulno.net
CMD ["./serveBuild"]
