#!/bin/bash

MY_PATH=`dirname "$0"`
cd "$MY_PATH"
MY_PATH=`pwd`

if [[ "$1" ]]; then
  PREFIX="$1"
fi
shift 1 # make sure to have parameters to forward

SERVICE_ID=""

cleanup() {
  kill "$SERVICE_ID" 2>/dev/null
  pkill -f node_modules/react-scripts/scripts/start.js
  pkill -f node_modules/serve/bin/serve.js
}

trap "cleanup" SIGINT SIGTERM

#yarn start "$@" &
./buildWithPrefix "$PREFIX" "$@" &
SERVICE_ID=$!
wait $SERVICE_ID
SERVICE_ID=""

# -C basically disables Cors: TODO: consider removing?
./serveBuild &
SERVICE_ID=$!
wait $SERVICE_ID

mv "$BACKUP_CONFIG_FILE" "$CONFIG_FILE" 2>/dev/null
