#!/bin/bash

set -m  # enable job control

# default prefix
PREFIX="https://ggia-dev.ulno.net"

CONFIG_FILE="src/Config.js"
BACKUP_CONFIG_FILE="$CONFIG_FILE.backup"

MY_PATH=`dirname "$0"`
cd "$MY_PATH"
MY_PATH=`pwd`

if [[ "$1" ]]; then
  PREFIX="$1"
fi

shift 1 # make sure to have paramters to forward

mv "$CONFIG_FILE" "$BACKUP_CONFIG_FILE"
cat << EOF > "$CONFIG_FILE"
const urlPrefix = "$PREFIX"
// // const urlPrefix = "https://ggia.ulno.net"
// const urlPrefix = "https://ggia-dev.ulno.net"
// const urlPrefix = "http://127.0.0.1:5000"
// const urlPrefix = "http://127.0.0.1:8000"
export default urlPrefix;
EOF

YARNID=""

function cleanup() {
  kill "$YARNID"
  pkill -f node_modules/react-scripts/scripts/start.js
}

trap "cleanup" SIGINT

yarn start "$@" &
YARNID=$!
fg

mv "$BACKUP_CONFIG_FILE" "$CONFIG_FILE"
